### ISSUE TITLE
Changing into human form in a dragon area breaks Sheena

### ISSUE THREAD

**Issue by pwaring** [RoxanneSHS/SheenaHD#1]
I have Sheena in my party in an otherwise unmodded BGII EE (2.6.6.0). She switched to dragon form automatically when I entered the lair of Adalon in the Underdark, which she seems to do whenever she is in the same area as another dragon. I rested and switched her back to human form, at which point she switched back to dragon form and then disappeared entirely. She still shows in my list of characters on the right hand side, but I can't select her individually or as part of the whole party. As a result, I'm stuck as I can't leave the current area ('you must gather your party before venturing forth'). I can't expel her using the Reform Party option either. This feels like it might be a bug where two scripts are conflicting with each other?

This might be a different issue, but I've also noticed that once the party has been turned into drow, Sheena seems to be locked into her dragon form (she looks like a drow but her portrait is dragon form, as are her stats - e.g. STR is 20).

I have a saved game from just before the problem occurred if that would be useful, and I have the console enabled to check variables etc.

**Comment by RoxanneSHS** [comment]
I suggest to try this
Prior to entering Adalon's lair, with console set C:SetGlobal("StartsSoon","GLOBAL",1) (you can also use near infinity).

**Comment by pwaring** [comment]
In the end I just left Sheena as she was - eventually she switched back from dragon form. There's still a bug whereby she will leave the party if she switches back during a dragon area though, at which point she will leave the party, but I can't offer a fix for that.
